### ISSUE TITLE
emmm，有人能帮我找到cookie在哪里吗？

### ISSUE THREAD

**Issue by 1055169799** [DYS763/paizi#1]
![捕获](https://user-images.githubusercontent.com/41286675/161864092-54844384-da2a-40f9-ba91-a82ad47dca8f.PNG)

**Comment by 1055169799** [comment]
然后是复制“cookie:xxxx=xxxxxxxxxxxxxxxxx”这段文字还是只复制“xxxx=xxxxxxxxxxxxxxxxx”，另外是放在哪个位置呢？
![捕获1](https://user-images.githubusercontent.com/41286675/161864792-737d1112-4590-4227-923d-8f08274f0bec.PNG)

**Comment by DYS763** [comment]
cookie只有你登陆过B站才会有，只复制xxxx=xxxxxxxxxxxxxxxx就好，放入"cookie":““内
