### ISSUE TITLE
插件没有任何反应

### ISSUE THREAD

**Issue by ElizaKzi** [DYS763/paizi#3]
应该是加载上插件了，但是却没有对指令做反馈，怪
![}6KKZFQ27XC{HF{2@B$MUTE](https://user-images.githubusercontent.com/63360445/165671833-2721d325-0d76-4dc3-8ac7-9d642e214578.png)
![{%2{UNJ ($DC4IXVC$PV@PE](https://user-images.githubusercontent.com/63360445/165671938-21c5d720-cec0-4b8f-ac30-19afb71255b4.png)
![4BVM$%LC7EQN2BY 38$Y_D](https://user-images.githubusercontent.com/63360445/165671977-3cecf7d8-c08a-4db8-9b4d-ac5239454f3f.png)

**Comment by DYS763** [comment]
有在群内开启功能么，功能默认是关闭的

**Comment by ElizaKzi** [comment]
> 有在群内开启功能么，功能默认是关闭的
非常感谢你的回答，实在没注意到是这个原因
如果可以的话，默认关闭其实可以标注在Readme
